language: objective-c
osx_image: xcode11.5
xcode_workspace: MarvelCharacters.xcworkspace
xcode_scheme: MarvelCharacters
xcode_sdk: iphonesimulator13.5

before_install:
  - pod install

script:
  - xcodebuild -workspace MarvelCharacters.xcworkspace -scheme 'MarvelCharacters' -sdk iphonesimulator13.5 -destination 'platform=iOS Simulator,name=iPhone 11,OS=13.5' -enableCodeCoverage YES test
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -J '^MarvelCharacters$'