language: objective-c
osx_image: xcode8.2
xcode_workspace: MarvelCharacters.xcworkspace
xcode_scheme: MarvelCharacters
xcode_sdk: iphonesimulator10.1

before_install:
  - pod install

script:
  - xcodebuild test -workspace MarvelCharacters.xcworkspace -scheme 'MarvelCharacters' -sdk iphonesimulator | xcpretty -c
  
after_success:
  - bash <(curl -s https://codecov.io/bash)