language: objective-c
osx_image: xcode8.1
xcode_workspace: MarvelCharacters.xcworkspace
xcode_scheme: MarvelCharacters
xcode_sdk: iphonesimulator10.1

before_install:
  - pod install

script:
  - xcodebuild -workspace MarvelCharacters.xcworkspace -scheme 'MarvelCharacters' -sdk iphonesimulator10.1 -destination 'platform=iOS Simulator,name=iPhone SE,OS=10.1' -enableCodeCoverage YES test
  
after_success:
  - bash <(curl -s https://codecov.io/bash)