language: objective-c
osx_image: xcode8.2
xcode_workspace: MarvelCharacters.xcworkspace
xcode_scheme: MarvelCharacters

before_install:
  - pod install

after_success:
  - bash <(curl -s https://codecov.io/bash)